require("code.settings.alien-biomes")
require("code.settings.clockwork")
require("code.settings.ir3-loaders-stacking")
require("code.settings.ir3")
require("code.settings.bream")
require("code.settings.intermodal-containers")
require("code.settings.cargo-ships")
require("code.settings.armoured-biters")